services:
  Demoniqus\StrategyBundle\Controller\StrategyApiController:
    alias: demoniqus.strategy.api.controller
    public: true

  demoniqus.strategy.api.controller:
    class: Demoniqus\StrategyBundle\Controller\StrategyApiController
    arguments:
      - '@jms_serializer'
      - '@request_stack'
      - '@evrinoma.dto.factory'
      - '@demoniqus.strategy.command.manager'
      - '@demoniqus.strategy.query.manager'
    autowire: true

  demoniqus.strategy.factory:
    class: Demoniqus\StrategyBundle\Factory\StrategyFactory
    public: true
    arguments:

  demoniqus.strategy.repository:
    class: Demoniqus\StrategyBundle\Repository\StrategyRepository
    public: true
    arguments:

  demoniqus.strategy.command.manager:
    class: Demoniqus\StrategyBundle\Manager\CommandManager
    arguments:
      - '@demoniqus.strategy.validator'
      - '@demoniqus.strategy.repository'
      - '@demoniqus.strategy.factory'
      - '@demoniqus.strategy.command.mediator'

  demoniqus.strategy.query.manager:
    class: Demoniqus\StrategyBundle\Manager\QueryManager
    arguments:
      - '@demoniqus.strategy.repository'

  demoniqus.strategy.validator:
    class: Demoniqus\StrategyBundle\Validator\StrategyValidator
    public: true
    arguments:

  Demoniqus\StrategyBundle\Validator\StrategyValidator:
    alias: demoniqus.strategy.validator

  demoniqus.strategy.query.mediator:
    class: Demoniqus\StrategyBundle\Mediator\QueryMediator
    public: true
    arguments:

  Demoniqus\StrategyBundle\Mediator\QueryMediator:
    alias: demoniqus.strategy.query.mediator

  Demoniqus\StrategyBundle\Mediator\QueryMediatorInterface:
    alias: demoniqus.strategy.query.mediator

  demoniqus.strategy.command.mediator:
    class: Demoniqus\StrategyBundle\Mediator\CommandMediator
    public: true
    arguments:

  Demoniqus\StrategyBundle\Mediator\CommandMediator:
    alias: demoniqus.strategy.command.mediator

  Demoniqus\StrategyBundle\Mediator\CommandMediatorInterface:
    alias: demoniqus.strategy.command.mediator
